In [1]:
from pathlib import Path
import pandas as pd
import numpy as np
import scipy.stats as ss
from scipy.interpolate import interp1d
from scipy.special import expit
from fractions import Fraction
from empiricaldist import Pmf, Cdf
import matplotlib.pyplot as plt
from collections import Counter
import statsmodels.formula.api as smfa

In [2]:
from data.utils import make_joint, plot_joint, plot_contour, normalize

In [3]:
x = [1, 3, 5]
y = [2, 4]
# np.meshgrid() 함수를 통해 grid 형성
# X * Y가 x와 y의 Tensor product
X, Y = np.meshgrid(x, y)
X, Y, X * Y

(array([[1, 3, 5],
        [1, 3, 5]]),
 array([[2, 2, 2],
        [4, 4, 4]]),
 array([[ 2,  6, 10],
        [ 4, 12, 20]]))

In [4]:
# 데이터프레임에 넣어서 이해를 쉽게
df = pd.DataFrame(X * Y, columns=x, index=y)
df

1   3   5
2  2   6  10
4  4  12  20